[database]
# The location of the database
url = "$HOME/.local/share/archive-organizer/database.db"

[server]
# Specifies the folder where downloaded files will go
download_folder = "/tmp/" # MUST end with a '/'

# Authorized tokes
authorization_tokens = ["secret"]

[scan]
# If true, will not make changes to the database
dry_run = true

# Map of patterns to automatically place tags using the `apply-tags` command
[scan.auto_tags]
"%Calibre Library%" = ["calibre", "ebook"]
