# -*- eval: (restclient-mode) -*-

# get all files
GET http://localhost:8000/files
Accept: application/json
Authorization: bearer secret

# get all file tags
GET http://localhost:8000/files/tags
Accept: application/json
Authorization: bearer secret

# get one file
GET http://localhost:8000/files/1
Accept: application/json
Authorization: bearer secret

# get tags of file
GET http://localhost:8000/files/1/tags
Accept: application/json
Authorization: bearer secret

# add tags to file
POST http://localhost:8000/files/1/tags
Content-Type: application/json
Accept: application/json
Authorization: bearer secret

["cowboys","horses"]

# download the contents of a file
GET http://localhost:8000/files/2/download-as/the_law_of_one_book_4.pdf
Authorization: bearer secret

# download the contents of a file, failing
GET http://localhost:8000/files/2/download-as/horses.epub
Accept: application/json
Authorization: bearer secret

# upload the contents of a file
POST http://localhost:8000/files
Content-Type: application/x-www-form-urlencoded
Content-Type: multipart/form-data; boundary=MyBountary
Accept: application/json
Authorization: bearer secret

--MyBoundary
Content-Disposition: form-data; name="file"; filename="notes.txt";
Content-Type: text/plain

Sticky Notes