# get all files
GET http://localhost:8000/files

# get all tags for all files
GET http://localhost:8000/files/tags

# get one file
GET http://localhost:8000/files/1

# get all tags for a single file
GET http://localhost:8000/files/1/tags

# get all tags for a single file
GET http://localhost:8000/files/2/download-as/the_law_of_one_book_4.pdf
Accept: application/json