# -*- eval: (restclient-mode) -*-

# get all files
GET http://localhost:8000/files
Accept: application/json
Authorization: bearer secret

# get all file tags
GET http://localhost:8000/files/tags
Accept: application/json
Authorization: bearer secret

# get one file
GET http://localhost:8000/files/1
Accept: application/json
Authorization: bearer secret

# get tags of file
GET http://localhost:8000/files/1/tags
Accept: application/json
Authorization: bearer secret

# add tags to file
POST http://localhost:8000/files/1/tags
ContentType: application/json
Accept: application/json
Authorization: bearer secret

["cowboys","horses"]

# download the contents of a file
GET http://localhost:8000/files/2/download-as/the_law_of_one_book_4.pdf
Accept: application/json
Authorization: bearer secret

# download the contents of a file, failing
GET http://localhost:8000/files/2/download-as/horses.epub
Accept: application/json
Authorization: bearer secret
