//! Feature-parity checker.
//!
//! Reconciles the canonical catalog in `FEATURES.toml` (workspace root) with the
//! `@feature: <id>` annotations carried by the implementations, regenerates
//! `FEATURE_MATRIX.md`, and fails on drift.
//!
//! Annotation syntax (the surrounding comment style does not matter — the scan
//! is purely textual):
//!   - Rust:      `/// @feature: documents.select_cover`
//!   - TS/Svelte: `// @feature: documents.select_cover`
//!
//! Surface → scanned tree:
//!   - `cosmic` → `cosmic/src`, `widgets/src`
//!   - `pwa`    → `pwa/src`
//!   - `rest`   → `core/src`
//!
//! Failure policy:
//!   - orphan tag      — `@feature:` id not present in the catalog
//!   - drift           — id annotated on a surface not listed in its `surfaces`
//!   - missing surface — a `surfaces` entry that is neither annotated nor listed
//!     in `gaps` (acknowledged backlog)
//!     Acknowledged `gaps` render as 🟡 and do NOT fail the build.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;
use std::path::PathBuf;

use serde::Deserialize;

const SURFACES: [&str; 3] = ["cosmic", "pwa", "rest"];
const SCAN_EXTENSIONS: [&str; 3] = ["rs", "ts", "svelte"];
const SKIP_DIRS: [&str; 4] = ["node_modules", "target", ".svelte-kit", "build"];

#[derive(Debug, Deserialize)]
struct Catalog {
    feature: Vec<Feature>,
}

#[derive(Debug, Deserialize)]
struct Feature {
    id: String,
    description: String,
    surfaces: Vec<String>,
    #[serde(default)]
    gaps: Vec<String>,
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR = <root>/core
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("core has a parent dir")
        .to_path_buf()
}

fn surface_dirs(surface: &str) -> Vec<&'static str> {
    match surface {
        "cosmic" => vec!["cosmic/src", "widgets/src"],
        "pwa" => vec!["pwa/src"],
        "rest" => vec!["core/src"],
        other => panic!("unknown surface {other}"),
    }
}

/// Recursively collect scannable files under `dir`.
fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if SKIP_DIRS.contains(&name) {
                continue;
            }
            collect_files(&path, out);
        } else if path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| SCAN_EXTENSIONS.contains(&e))
        {
            out.push(path);
        }
    }
}

/// Parse the feature id following a `@feature:` marker on a line.
fn parse_tag(line: &str) -> Option<String> {
    let idx = line.find("@feature:")?;
    let rest = &line[idx + "@feature:".len()..];
    let id: String = rest
        .trim_start()
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | '-'))
        .collect();
    if id.is_empty() { None } else { Some(id) }
}

/// id → surface → list of locations
fn scan_annotations(root: &Path) -> BTreeMap<String, BTreeMap<String, Vec<String>>> {
    let mut found: BTreeMap<String, BTreeMap<String, Vec<String>>> = BTreeMap::new();
    for surface in SURFACES {
        for rel in surface_dirs(surface) {
            let mut files = Vec::new();
            collect_files(&root.join(rel), &mut files);
            for file in files {
                let Ok(content) = fs::read_to_string(&file) else {
                    continue;
                };
                for (n, line) in content.lines().enumerate() {
                    if let Some(id) = parse_tag(line) {
                        let loc = format!(
                            "{}:{}",
                            file.strip_prefix(root).unwrap_or(&file).display(),
                            n + 1
                        );
                        found
                            .entry(id)
                            .or_default()
                            .entry(surface.to_string())
                            .or_default()
                            .push(loc);
                    }
                }
            }
        }
    }
    found
}

fn render_matrix(
    catalog: &[Feature],
    found: &BTreeMap<String, BTreeMap<String, Vec<String>>>,
) -> String {
    let mut out = String::new();
    out.push_str("# Feature parity matrix\n\n");
    out.push_str(
        "_Generated by `core/tests/feature_matrix.rs` from `FEATURES.toml` + `@feature:` \
         code annotations. Do not edit by hand — run `cargo nextest run -p read-flow-core \
         feature_matrix` (or `cargo test`) to regenerate._\n\n",
    );
    out.push_str("Legend: ✅ implemented · 🟡 planned (acknowledged gap) · ❌ missing · ⚠️ unexpected · blank = not targeted\n\n");
    out.push_str("| Feature | COSMIC | PWA | REST | Description |\n");
    out.push_str("|---|:---:|:---:|:---:|---|\n");

    for f in catalog {
        let surfaces: BTreeSet<&str> = f.surfaces.iter().map(String::as_str).collect();
        let gaps: BTreeSet<&str> = f.gaps.iter().map(String::as_str).collect();
        let hits = found.get(&f.id);
        let mut cells = Vec::new();
        for surface in SURFACES {
            let is_found = hits.is_some_and(|m| m.contains_key(surface));
            let cell = if surfaces.contains(surface) {
                if is_found {
                    "✅"
                } else if gaps.contains(surface) {
                    "🟡"
                } else {
                    "❌"
                }
            } else if is_found {
                "⚠️"
            } else {
                ""
            };
            cells.push(cell);
        }
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            f.id, cells[0], cells[1], cells[2], f.description
        ));
    }

    // Summary counts.
    let total = catalog.len();
    out.push_str(&format!("\n_{total} features tracked._\n"));
    out
}

#[test]
fn feature_matrix_is_consistent() {
    let root = workspace_root();
    let catalog_path = root.join("FEATURES.toml");
    let raw = fs::read_to_string(&catalog_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", catalog_path.display()));
    let catalog: Catalog = toml::from_str(&raw).expect("parse FEATURES.toml");

    let mut errors: Vec<String> = Vec::new();

    // Catalog self-consistency.
    let mut seen = BTreeSet::new();
    for f in &catalog.feature {
        if !seen.insert(f.id.as_str()) {
            errors.push(format!("duplicate feature id in catalog: {}", f.id));
        }
        for s in f.surfaces.iter().chain(f.gaps.iter()) {
            if !SURFACES.contains(&s.as_str()) {
                errors.push(format!("feature {} references unknown surface {s}", f.id));
            }
        }
        for g in &f.gaps {
            if !f.surfaces.contains(g) {
                errors.push(format!(
                    "feature {} lists gap {g} that is not in its surfaces",
                    f.id
                ));
            }
        }
    }

    let found = scan_annotations(&root);

    // Orphan + drift: every discovered tag must map to a catalog feature, on a
    // surface that feature targets.
    for (id, by_surface) in &found {
        match catalog.feature.iter().find(|f| &f.id == id) {
            None => {
                let locs: Vec<String> = by_surface.values().flatten().cloned().collect();
                errors.push(format!(
                    "orphan @feature tag `{id}` (not in FEATURES.toml) at: {}",
                    locs.join(", ")
                ));
            }
            Some(f) => {
                for (surface, locs) in by_surface {
                    if !f.surfaces.contains(surface) {
                        errors.push(format!(
                            "drift: `{id}` annotated on surface `{surface}` not in its \
                             catalog surfaces {:?} at: {}",
                            f.surfaces,
                            locs.join(", ")
                        ));
                    }
                }
            }
        }
    }

    // Missing: a targeted surface that is neither annotated nor an acknowledged gap.
    for f in &catalog.feature {
        for surface in &f.surfaces {
            let annotated = found
                .get(&f.id)
                .is_some_and(|m| m.contains_key(surface.as_str()));
            let acknowledged = f.gaps.contains(surface);
            if !annotated && !acknowledged {
                errors.push(format!(
                    "missing: feature `{}` targets surface `{surface}` but has no \
                     @feature annotation there (add the annotation, or list `{surface}` \
                     in its `gaps` if it is intentionally not done yet)",
                    f.id
                ));
            }
        }
    }

    // Regenerate the human-readable matrix regardless of pass/fail.
    let matrix = render_matrix(&catalog.feature, &found);
    let matrix_path = root.join("FEATURE_MATRIX.md");
    fs::write(&matrix_path, &matrix).expect("write FEATURE_MATRIX.md");

    assert!(
        errors.is_empty(),
        "feature parity check failed:\n  - {}",
        errors.join("\n  - ")
    );
}
